### ISSUE TITLE
Add CAMIS

### ISSUE THREAD

**Issue by nanxstats** [hidyverse/awesome-R-clinical-reporting#1]
Here is a new resource from a cross-industry group working on comparing analysis method implementations in software: https://psiaims.github.io/CAMIS/

I think this a useful resource to add because it helps increase awareness of the potential source of common differences between software, and ultimately, saves individual investigation time.

See this R Consortium [blog post](https://www.r-consortium.org/blog/2023/05/31/comparing-analysis-method-implementations-in-software-camis) for more context about the project.

**Comment by hidyverse** [comment]
TYSM!

I added CAMIS to the featured list. I also added to A&R - do you think it fits better under dev?

**Comment by nanxstats** [comment]
Great! Looking flawless. I feel if we have to categorize... it might fit dev a bit better than A&R as it's more about "computing with proper verification" instead of analysis workflow automation. But I will let you make the decision.

**Comment by nanxstats** [comment]
This has been added by https://github.com/hidyverse/awesome-R-clinical-reporting/commit/9e0ad35ca67914b0c9f244b49e341302805c63ab.
