### ISSUE TITLE
add packages for tabular output

### ISSUE THREAD

**Issue by Xyarz** [hidyverse/awesome-R-clinical-reporting#7]
Hi @hidyverse,
very useful packages for tabular output are also:
[reactable](https://glin.github.io/reactable/index.html) - self explanatory
[gt](https://gt.rstudio.com/articles/intro-creating-gt-tables.html) - very very great functionality as well as flexibility on a cell level basis. Can do plots in cells, cell highlighting etc.
[tfrmt](https://gsk-biostatistics.github.io/tfrmt/) - very handy tool to set up tabular structures based on ARDs
[rtables](https://insightsengineering.github.io/rtables/main/) - pharmaverse and used inside TEAL etc.
[falcon](https://pharmaverse.github.io/falcon/) - pharmaverse FDA safety tables and figures
[TLG catalog by Roche](https://insightsengineering.github.io/tlg-catalog/)

**Comment by hidyverse** [comment]
Hi @Xyarz, thanks - let's add these! Please feel free to open a PR if you have time for this change before I get to it. 

One thing regarding pharmaverse packages in the future of this list. I love the pharmaverse packages and want to include them all without being too redundant or choosing favorites. What are your thoughts on adding them all versus adding pharmaverse as one group of items?

**Comment by hidyverse** [comment]
Added more of these with [cd40579](https://github.com/hidyverse/awesome-R-clinical-reporting/commit/cd40579202ab123634ff365d89f07c667509fe3f)
